import {
  TEMPERATURE_OPTIONS,
  FUNNEL_STAGE_OPTIONS,
  SOURCE_OPTIONS,
  CALL_TYPE_OPTIONS,
  TYPE_ETABLISSEMENT_OPTIONS,
} from './fieldOptions'

export type PropertyType =
  | 'slug'
  | 'fk'
  | 'string'
  | 'text'
  | 'url'
  | 'enum'
  | 'multi-csv'
  | 'int'
  | 'date'

export type PropertyMeta = {
  table: 'companies' | 'contacts' | 'calls'
  name: string
  type: PropertyType
  source: string
  description: string
  enumValues?: readonly string[]
  cascade?: 'on-company-fallback-contact' | 'never'
  required?: boolean
  writtenBy: string[]
}

export const PROPERTIES: PropertyMeta[] = [
  // companies.tsv
  {
    table: 'companies',
    name: 'id',
    type: 'slug',
    source: 'manual / skill',
    required: true,
    description: "Cle primaire. Slug ASCII minuscules, kebab-case (ex: groupe-korian).",
    writtenBy: ['manual'],
  },
  {
    table: 'companies',
    name: 'name',
    type: 'string',
    source: 'manual / web',
    required: true,
    description: "Nom de l'etablissement ou du groupe (casse et accents reels).",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'companies',
    name: 'phone',
    type: 'string',
    source: 'manual / web',
    description: "Numero de telephone de l'etablissement (format libre, ex: 04 94 24 31 59).",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'companies',
    name: 'address',
    type: 'string',
    source: 'manual / web',
    description: "Adresse postale (ex: 128 rue Boucicaut, 92260 Fontenay-aux-Roses).",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'companies',
    name: 'linkedin_url',
    type: 'url',
    source: 'manual / web',
    description: "URL LinkedIn officielle de l'etablissement ou du groupe.",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'companies',
    name: 'tagline',
    type: 'text',
    source: 'manual / web',
    description: "Phrase courte resumant le contexte (ex: Groupe de 12 EHPAD, utilise NETSoins).",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'companies',
    name: 'funnel_stage',
    type: 'enum',
    enumValues: FUNNEL_STAGE_OPTIONS,
    source: 'manual',
    description: "Etape dans le cycle de vente. Se repercute sur les contacts.",
    cascade: 'on-company-fallback-contact',
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'companies',
    name: 'employees',
    type: 'string',
    source: 'manual / web / LinkedIn',
    description: "Nombre de soignants approximatif. Accepte un entier, une plage (50-100) ou une borne ouverte (200+).",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'companies',
    name: 'type_etablissement',
    type: 'enum',
    enumValues: TYPE_ETABLISSEMENT_OPTIONS,
    source: 'manual',
    description: "Groupe (plusieurs sites) ou Independant (un seul site). Signal decisif co-egal a NETSoins.",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'companies',
    name: 'nb_etablissements',
    type: 'int',
    source: 'manual / web',
    description: "Nombre de sites dans le groupe. Vide si type_etablissement = Independant.",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'companies',
    name: 'DUI',
    type: 'string',
    source: 'manual / web',
    description: "Logiciel dossier usager utilise par l'etablissement (ex: NETSoins, OSIRIS, Livia).",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'companies',
    name: 'summary',
    type: 'text',
    source: 'manual',
    description: "1 a 3 lignes decrivant l'etablissement.",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'companies',
    name: 'notes',
    type: 'text',
    source: 'manual',
    description: "Notes libres.",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'companies',
    name: 'next_action',
    type: 'text',
    source: 'manual',
    description: "Prochaine action au niveau de l'etablissement. Si vide, remonte depuis le contact le plus recent.",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'companies',
    name: 'created_by',
    type: 'enum',
    enumValues: ['me', 'Claude', 'migration'],
    source: 'auto',
    description: "Qui a cree la ligne.",
    writtenBy: ['app', 'migration'],
  },
  {
    table: 'companies',
    name: 'created_at',
    type: 'date',
    source: 'auto',
    description: "YYYY-MM-DD, date de creation.",
    writtenBy: ['app', 'migration'],
  },
  {
    table: 'companies',
    name: 'updated_by',
    type: 'enum',
    enumValues: ['me', 'Claude', 'migration'],
    source: 'auto (POST API)',
    description: "Qui a mis a jour la ligne en dernier. Auto-injecte.",
    writtenBy: ['app (auto)', 'migration'],
  },
  {
    table: 'companies',
    name: 'updated_at',
    type: 'date',
    source: 'auto (POST API)',
    description: "YYYY-MM-DD de la derniere mise a jour. Auto-injecte.",
    writtenBy: ['app (auto)', 'migration'],
  },

  // contacts.tsv
  {
    table: 'contacts',
    name: 'id',
    type: 'slug',
    source: 'manual / skill',
    required: true,
    description: "Slug prenom-nom (ex: marie-dupont).",
    writtenBy: ['manual'],
  },
  {
    table: 'contacts',
    name: 'company_id',
    type: 'fk',
    source: 'manual / skill',
    description: "FK vers companies.id. Peut etre vide (contact orphelin).",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'contacts',
    name: 'name',
    type: 'string',
    source: 'manual / LinkedIn',
    required: true,
    description: "Prenom Nom, casse et accents reels.",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'contacts',
    name: 'job_title',
    type: 'string',
    source: 'manual / LinkedIn',
    description: "Poste exact (ex: Directeur, Cadre de sante).",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'contacts',
    name: 'linkedin',
    type: 'url',
    source: 'manual / LinkedIn',
    description: "URL du profil LinkedIn personnel. Cle de deduplication principale.",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'contacts',
    name: 'email',
    type: 'string',
    source: 'manual / web / LinkedIn',
    description: "Email professionnel. Optionnel.",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'contacts',
    name: 'phone',
    type: 'string',
    source: 'manual / web',
    description: "Numero de telephone (format libre, ex: +33 6 12 34 56 78). Optionnel.",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'contacts',
    name: 'funnel_stage',
    type: 'enum',
    enumValues: FUNNEL_STAGE_OPTIONS,
    source: 'fallback contact',
    description: "Utilise seulement si pas de company_id (sinon herite de l'etablissement).",
    cascade: 'on-company-fallback-contact',
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'contacts',
    name: 'temperature',
    type: 'enum',
    enumValues: TEMPERATURE_OPTIONS,
    source: 'manual',
    description: "Niveau d'interet percu du contact. Toujours au niveau du contact.",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'contacts',
    name: 'recap',
    type: 'text',
    source: 'manual',
    description: "Vue 360 de l'historique avec ce contact. Evolue dans le temps.",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'contacts',
    name: 'next_action',
    type: 'text',
    source: 'manual',
    description: "Prochaine etape commerciale, une ligne.",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'contacts',
    name: 'created_at',
    type: 'date',
    source: 'auto',
    description: "YYYY-MM-DD, date de creation.",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'contacts',
    name: 'source',
    type: 'enum',
    enumValues: SOURCE_OPTIONS,
    source: 'manual',
    description: "Comment ce contact est entre dans le CRM.",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'contacts',
    name: 'created_by',
    type: 'enum',
    enumValues: ['me', 'Claude', 'migration'],
    source: 'auto',
    description: "Qui a cree la ligne.",
    writtenBy: ['app', 'migration'],
  },
  {
    table: 'contacts',
    name: 'updated_by',
    type: 'enum',
    enumValues: ['me', 'Claude', 'migration'],
    source: 'auto (POST API)',
    description: "Qui a mis a jour la ligne en dernier. Auto-injecte.",
    writtenBy: ['app (auto)', 'migration'],
  },
  {
    table: 'contacts',
    name: 'updated_at',
    type: 'date',
    source: 'auto (POST API)',
    description: "YYYY-MM-DD de la derniere mise a jour. Auto-injecte.",
    writtenBy: ['app (auto)', 'migration'],
  },

  // calls.tsv
  {
    table: 'calls',
    name: 'id',
    type: 'slug',
    source: 'manual / skill',
    required: true,
    description: "Format <contact-slug>-<YYYY-MM-DD>.",
    writtenBy: ['manual'],
  },
  {
    table: 'calls',
    name: 'contact_id',
    type: 'fk',
    source: 'manual / skill',
    required: true,
    description: "FK vers contacts.id. Jamais vide.",
    writtenBy: ['manual'],
  },
  {
    table: 'calls',
    name: 'date',
    type: 'date',
    source: 'manual',
    required: true,
    description: "YYYY-MM-DD, date de l'echange.",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'calls',
    name: 'type',
    type: 'enum',
    enumValues: CALL_TYPE_OPTIONS,
    source: 'manual',
    description: "Canal de l'echange.",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'calls',
    name: 'summary',
    type: 'text',
    source: 'manual',
    description: "Resume de l'echange, points cles, objections.",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'calls',
    name: 'next_action',
    type: 'text',
    source: 'manual',
    description: "Action decidee pendant l'echange.",
    writtenBy: ['app', 'manual'],
  },
  {
    table: 'calls',
    name: 'created_by',
    type: 'enum',
    enumValues: ['me', 'Claude', 'migration'],
    source: 'auto',
    description: "Qui a cree la ligne.",
    writtenBy: ['app', 'migration'],
  },
  {
    table: 'calls',
    name: 'created_at',
    type: 'date',
    source: 'auto',
    description: "YYYY-MM-DD, date de creation.",
    writtenBy: ['app', 'migration'],
  },
  {
    table: 'calls',
    name: 'updated_by',
    type: 'enum',
    enumValues: ['me', 'Claude', 'migration'],
    source: 'auto (POST API)',
    description: "Qui a mis a jour la ligne en dernier. Auto-injecte.",
    writtenBy: ['app (auto)', 'migration'],
  },
  {
    table: 'calls',
    name: 'updated_at',
    type: 'date',
    source: 'auto (POST API)',
    description: "YYYY-MM-DD de la derniere mise a jour. Auto-injecte.",
    writtenBy: ['app (auto)', 'migration'],
  },
]
